### ISSUE TITLE
Binder no funciona

### ISSUE THREAD

**Issue by jmloyola** [PrACiDa/EBAD#14]
Luego de agregar el archivo `environment.yml` se crea el entorno y se puede ejecutar.
Pero al importar _arviz_ ocurre el siguiente error: `ModuleNotFoundError: No module named 'netCDF4'`.
¿Tendré que agregar el paquete `netCDF4`? Me resulta raro que no lo instale automáticamente cuando se instala arviz.
Por otro lado tengo que agregar un archivo `postBuild` de binder para que ejecute el comando `export MKL_THREADING_LAYER=GNU` luego de instalar todo y de esta forma no tire warnings.

**Comment by aloctavodia** [comment]
ArviZ está cambiando muy rápido! Acabo de agregar netCDF4 como requerimiento de ArviZ.

**Comment by jmloyola** [comment]
Ya funciona binder :smile:
