### ISSUE TITLE
Quisiera saber si hay avances en Regresión lineal múltiple

### ISSUE THREAD

**Issue by malliwi88** [PrACiDa/EBAD#6]
Buena noche,

quisiera contribuir, mi interés particular es en realizar una regresión multivariable empleando modelos bayesianos, cualquier ayuda me vendría bien para poder aportar.

Por lo pronto iniciaré con revisar y comentar si encuentro errores.

por cierto este es mi correo, pues creo que el gitter esta muerto william.trigos@gmail.com

**Comment by aloctavodia** [comment]
Hola @malliwi88 Gracias por tu interés y ganas de contribuir. El capítulo 4 incluye regresión lineal múltiple solo que hay un error en el título, pero ya está arreglado. Cierro por ahora este issue, pero reabrilo en caso de ser necesario.

**Comment by aloctavodia** [comment]
Por cierto, este repositorio no tiene un gitter asociado (o se me hizo lío?)
